version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.2.0
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin # Log in to Docker Hub using the environment variables
      - run: docker build -t YOUR_DOCKER_IMAGE_NAME .
      - run: docker push YOUR_DOCKER_IMAGE_NAME
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
